'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MillionaireGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Correct_Answer_Fill_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Correct_Answer_Fill_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Correct_Answer_Fill_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Correct_Answer_Fill_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Final_Answer_Fill_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Final_Answer_Fill_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Final_Answer_Fill_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Final_Answer_Fill_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Large_Strap_Fill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Large_Strap_Fill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Normal_Answer_Fill_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Normal_Answer_Fill_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_Normal_Answer_Fill_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_Normal_Answer_Fill_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_tree_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0_tree_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_tree_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_tree_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _36973() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("36973", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ata_end() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ata_end", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ata_start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ata_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ata_vote() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ata_vote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fastest_finger_read_answer_order() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fastest_finger_read_answer_order", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fastest_finger_read_question() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fastest_finger_read_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fastest_finger_think() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fastest_finger_think", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fff_correct_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fff_correct_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fff_fastest_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fff_fastest_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fff_idle_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fff_idle_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property game_resume() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("game_resume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property hello_long() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hello_long", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_5050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_5050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_5050_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_5050_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_5050_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_5050_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_audience() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_audience", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_audience_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_audience_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_audience_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_audience_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_double() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_double", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_double_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_double_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_double_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_double_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_host() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_host", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_host_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_host_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_host_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_host_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_phone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_phone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_phone_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_phone_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_phone_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_phone_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_plusone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_plusone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_plusone_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_plusone_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_plusone_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_plusone_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_switch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_switch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_switch_bling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_switch_bling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ll_switch_used() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ll_switch_used", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mg_tree_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mg_tree_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property paf_countdown() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("paf_countdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q1_to_q4_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q1_to_q4_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q1_to_q5_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q1_to_q5_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q10_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q10_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q10_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q10_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q10_correct_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q10_correct_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q10_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q10_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q11_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q11_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q11_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q11_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q11_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q11_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q12_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q12_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q12_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q12_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q12_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q12_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q13_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q13_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q13_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q13_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q13_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q13_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q14_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q14_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q14_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q14_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q14_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q14_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q15_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q15_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q15_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q15_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q15_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q15_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q5_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q5_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q6_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q6_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q6_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q6_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q6_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q6_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q7_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q7_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q7_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q7_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q7_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q7_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q8_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q8_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q8_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q8_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q8_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q8_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q9_bed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q9_bed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q9_correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q9_correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property q9_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("q9_lose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property stq_new_question_flip() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("stq_new_question_flip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property stq_reveal_correct_answer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("stq_reveal_correct_answer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property stq_start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("stq_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tree_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property triangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property winning_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("winning_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property winning_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("winning_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property winning_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("winning_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
